[package]
name = "ul-core"
description = "Jezgra ulEditora: virtualni datotečni sustav i model dokumenta."
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
ul-formats = { path = "../ul-formats" }
serde = { workspace = true }
thiserror = { workspace = true }
