[package]
name = "ul-core"
description = "ulEditor core: virtual file system and document model."
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
ul-formats = { path = "../ul-formats" }
serde = { workspace = true }
thiserror = { workspace = true }
